### ISSUE TITLE
Compare Performance of Bulirsh-Stoer vs RK steppers

### ISSUE THREAD

**Issue by dmitrySorokin** [jonapost/field_propagation#15]
Using  testNTST compare the performance (time, number of field calls) of the following steppers / methods:
-  Classical RK4 - baseline
-  Cash Karp
-  Bogacki Shampine 45
-  Bulirsch Stoer
### Results

| stepper | macros | Number calls to field | Event real time |
| --- | --- | --: | --: |
| ClassicalRK4 | run2a.mac | 253788526 | 0.156 +- 0.00331 (sec) |
|  | run2b.mac | 1292629168 | 0.44 +- 0.00859 (sec) |
|  | run2c.mac | 4285506533 | 2.6 +- 0.0428 (sec) |
| CashKarpRKF45 | run2a.mac | 192322606 | 0.15 +- 0.00311 (sec) |
|  | run2b.mac | 663524962 | 0.309 +- 0.00573 (sec) |
|  | run2c.mac | 2043095874 | 2.38 +- 0.0416 (sec) |

**Comment by jonapost** [comment]
I have made some runs with a revised version of the 'run2b.mac'  file and a reduced statistics one that samples 100 events only.  I do not have reliable timings, as I still had warnings for most runs, so I quote only the number of calls.

### Results for 100 events with benchmarks/transportation/NTST

| stepper | run id | Number calls to field |
| --- | --- | --: |
| CashKarp | 01 | 204020990 |
| BogackiShampine23 | 01 | 243974842 |
| BogackiShampine45 | 01 | 235649070 |
| BogackiShampine45 | 02 | 238250832 |
| DormandPrince745 | 01 | 169120338 |
| Tsitouras45 | 01 | 313456273 |
| ------------------------ | ------------- | -----: |
| BogackiShampine23 | 04 | 252788084 |
| BogackiShampine45 | 03 | 238250832 |
| ClassicalRK4 | 03 | 311325825 |
| Tsitouras45 | 02 | 293274304 |

In the first runs (run id = 01, 02) there were still many warnings.  For the latter runs I used the workaround to avoid triggering the warnings about the non-unit normal.

**Comment by dmitrySorokin** [comment]
Error estimation in Boost Bulirsch-Stoer:
![render](https://cloud.githubusercontent.com/assets/16517171/15538259/b63568b4-2283-11e6-8a47-16d9224e1734.png)
To compare with ClassicalRK4 I did the same error estimation in it too. 

Bulirsch-Stoer is built in Boost as a driver routine. This means that I don't have access to the stepper. 
I have not implement FindNextChord function for Bulirsch-Stoer. When I am given a step I just call Bulirsch-Stoer to integrate over this interval. 

| stepper | macros | Number calls to field |
| --- | --- | --: |
| Bulirsch-Stoer | run2a.mac | 335238606 |
| ClassicalRK4 | run2a.mac | 279192243 |
| ClassicalRK4 (without FindNextChord ) | run2a.mac | 1051873974 |

**Comment by dmitrySorokin** [comment]
Using BulirschStoerDriver I get the following results.

| macros | Number calls to field |
| --: | --: |
| run2a.mac | 181356502 |
| run2b.mac | 850386178 |
| run2c.mac | 2689760134 |

**Comment by jonapost** [comment]
Great to see the results now.  Can you clarify whether these are total number of field calls (from CachedMagneticField) or number of separate, non-cached evaluations ?
A quick check shows that Bulirsch-Stoer is about 6% better than Cash-Karp for case 'a' and 30% worse for cases 'b' & 'c'

It would be good also to separate number of calls for QuickAdvance vs. AccurateAdvance  (and, if possible, the time), in order to clarify the cost of the current chosen method for QuickAdvance in Bulirsch-Stoer. As you say, it is likely an important contribution.

**Comment by jonapost** [comment]
To summarise the number of calls per 'event' (3 columns on the left) and relative differences on the right: first comparing vs ClassicalRK4 (= C4) and then vs Cash-Karp (CK or CK45)

| Macro | ClassicalRK4 | Cash-Karp | Bulirsch-Stoer | CK45 vs C4 | BS vs C4 | BS vs CK45 |
| --- | --- | --- | --- | --- | --- | --- |
| 2a | 253'789 | 192'323 | 181'357 | 24.2 | 28.5 | 5.7 |
| 2b | 1'292'629 | 663'525 | 850'386 | 48.7 | 34.2 | -28.2 |
| 2c | 4'285'507 | 2'043'096 | 2'689'760 | 52.3 | 37.2 | -31.7 |
|  | #calls | # calls | #calls | %diff | %diff | %diff |

or 'raw' from spreadsheet

![image](https://cloud.githubusercontent.com/assets/2183871/16053688/2f748476-326a-11e6-8036-7c0414f10b84.png)
